- name: Restart healthCheck.timer
  systemd:
    name: healthCheck.timer
    state: restarted
    enabled: yes

- name: Restart webhookHandler.timer
  systemd:
    name: webhookHandler.timer
    state: restarted
    enabled: yes
