- hosts: webservers
  become: true
  become_user: controller
  become_method: sudo
  roles:
    - common
    - webServer


- hosts: prometheus
  become: true
  become_user: controller
  become_method: sudo
  roles:
    - common
    - prometheus
    - healthCheck
    