- name: Copy health check script
  copy:
    src: roles/healthCheck/files/healthCheck.sh
    dest: /usr/local/bin/healthCheck.sh
    mode: '0755'

- name: Create systemd service file for health check
  copy:
    dest: /etc/systemd/system/healthCheck.service
    content: |
      [Unit]
      Description=Health Check Script
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/healthCheck.sh
      Restart=always
      Type=simple
  notify: Reload systemd

- name: Create systemd timer file for health check
  copy:
    dest: /etc/systemd/system/healthCheck.timer
    content: |
      [Unit]
      Description=Run Health Check Every 1 Second

      [Timer]
      OnUnitActiveSec=1s
      Unit=healthCheck.service

      [Install]
      WantedBy=timers.target
  notify: Reload systemd

- name: Enable health check timer
  systemd:
    name: healthCheck.timer
    enabled: yes
    state: started
