# Updated tasks/main.yml with Prometheus and monitoring stack integration
- name: Ensure Docker Compose is installed
  apt:
    name: docker-compose
    state: present

- name: Create directories for Prometheus configuration
  file:
    path: "/etc/prometheus"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create directories for Alertmanager configuration
  file:
    path: "/etc/alertmanager"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"
    owner: root
    group: root
    mode: 0644
  notify: Restart Prometheus services

- name: Copy Alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "/etc/alertmanager/alertmanager.yml"
    owner: root
    group: root
    mode: 0644
  notify: Restart Alertmanager services

- name: Copy Prometheus alert rules
  template:
    src: alert_rules.yml.j2
    dest: "/etc/prometheus/alert_rules.yml"
    owner: root
    group: root
    mode: 0644
  notify: Restart Prometheus services

- name: Create directory for Prometheus stack
  file:
    path: "/etc/prometheus-stack"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "/etc/prometheus-stack/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: Deploy monitoring stack using Docker Compose
  shell: docker compose up -d
  args:
    chdir: "/etc/prometheus-stack"
  register: monitoring_stack_status
  changed_when: monitoring_stack_status.stdout.find("Creating") != -1
  notify:
    - Restart Prometheus services
    - Restart Alertmanager services
    - Restart Push Gateway services
