# tasks/main.yml
- name: Install required tools
  apt:
    name:
      - curl
      - wget
      - git
      - python3-pip
      - gnupg  # Ensure gpg is available
    state: present
    update_cache: true

- name: Add Docker GPG key
  ansible.builtin.command: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
    gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true
