- name: Install required dependencies for Docker
  package:
    name:
      - ca-certificates
      - curl
    state: present

- name: Check if keyring directory exists
  stat:
    path: /etc/apt/keyrings
  register: keyring_stat

- name: Add Docker's official GPG key using keyring if directory exists
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
  when: keyring_stat.stat.exists
  args:
    creates: /etc/apt/keyrings/docker.asc

- name: Add Docker's official GPG key using trusted.gpg.d if keyring directory doesn't exist
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  when: not keyring_stat.stat.exists
  args:
    creates: /etc/apt/trusted.gpg.d/docker.asc

- name: Add Docker repository to Apt sources
  shell: |
    echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: true
