# Updated tasks/main.yml with handler integration
- name: Ensure Docker Compose is installed
  apt:
    name: docker-compose
    state: present

- name: Create directories for custom HTML
  file:
    path: "/var/www/{{ inventory_hostname }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy custom index.html
  template:
    src: index.html.j2
    dest: "/var/www/{{ inventory_hostname }}/index.html"
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx services

- name: Copy Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "/var/www/{{ inventory_hostname }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx services

- name: Check if Docker Compose services are up-to-date
  shell: docker compose config
  args:
    chdir: "/var/www/{{ inventory_hostname }}"
  register: compose_config_check
  changed_when: false

- name: Start Nginx using Docker Compose if config has changed
  shell: docker compose up -d
  args:
    chdir: "/var/www/{{ inventory_hostname }}"
  when: compose_config_check.changed
  notify: Restart Nginx services
