---
# tasks/main.yml
- name: Pull Nginx image
  command: docker pull nginx

- name: Create directories for custom HTML
  file:
    path: "/var/www/{{ webserver_name }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy custom index.html
  template:
    src: index.html.j2
    dest: "/var/www/{{ webserver_name }}/index.html"
    owner: root
    group: root
    mode: 0644

- name: Deploy Nginx container
  shell: |
    docker run --name {{ webserver_name }} -d \
    -p 80:80 \
    -v /var/www/{{ webserver_name }}/index.html:/usr/share/nginx/html/index.html:ro \
    nginx
  args:
    creates: "/var/lib/docker/containers/{{ webserver_name }}"

- name: Ensure container is running
  shell: |
    docker start {{ webserver_name }} || docker restart {{ webserver_name }}
