- name: Restart Push Gateway services
  shell: docker compose restart pushgateway
  args:
    chdir: "/etc/prometheus-stack"

- name: Restart Alertmanager services
  shell: docker compose restart alertmanager
  args:
    chdir: "/etc/prometheus-stack"

- name: Restart Prometheus services
  shell: docker compose restart prometheus
  args:
    chdir: "/etc/prometheus-stack"
